JuguetesUsados/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

#from apps.intercambio import views

urlpatterns = [
    path('',include('apps.usuarios.urls')),
    path('admin/', admin.site.urls),
    path('usuarios/', include('apps.usuarios.urls')),
    path('producto/', include('apps.producto.urls')),
    path('galeria/', include('apps.galeria.urls')),
    path('intercambio/', include('apps.intercambio.urls')),
    path('analisis/', include('apps.analisis.urls')),
    #path('productos/', include('apps.productos.urls')),
] + static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/galeria/urls.py
from django.urls import path
from apps.galeria import views

urlpatterns = [
    path('galeria_ap/<int:id_infante>', views.verGaleria_ap, name="galeria_ap"),
    path('galeria_in/<int:id_infante>', views.verGaleria_in, name="galeria_in"),
    path('filtrarGaleria/<int:id_infante>', views.filtrarGaleria, name="filtrarGaleria"),
    # path('galeria_config/<int:id_galeria>/<int:limite>', views.configGaleria, name="galeria_config"),
    path('galeria_config/<int:id_galeria>', views.configGaleria, name="galeria_config"),
]

apps/galeria/models.py
from django.db import models
from apps.usuarios.models import Infante

# Create your models here.
class Galeria(models.Model):
    #atributos
    limiteProductos = models.PositiveIntegerField(blank=True,null=True)
    #LLaves foraneas
    infante = models.OneToOneField(Infante, on_delete=models.CASCADE, blank=True,null=True)

apps/producto/models.py
import qrcode
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO

from django.http import HttpResponseRedirect
from django.urls import reverse

from django.db import models
from apps.usuarios.models import Infante
from apps.producto.Choices import Categoria, Desarrollo
from apps.galeria.models import Galeria

from django.core.files import File
import os



# Create your models here.
class ProductoIntercambio(models.Model):
    #atributos
    foto= models.ImageField(upload_to='juguetes')
    nombre=models.CharField(max_length=20)
    categoria=models.CharField(max_length=2, choices= Categoria, default='DV')
    estado=models.CharField(max_length=20, default='deseado')
    estado_d=models.CharField(max_length=250, blank=True,null=True)
    marca=models.CharField(max_length=250, blank=True,null=True)
    modelo=models.CharField(max_length=250, blank=True,null=True)
    serie=models.CharField(max_length=250, blank=True,null=True)
    anno=models.CharField(max_length=250, blank=True,null=True)
    tamano=models.CharField(max_length=250, blank=True,null=True)
    material=models.CharField(max_length=250, blank=True,null=True)

    #LLaves foraneas
    infante = models.PositiveIntegerField(default=0) #infante que se queda con juguete
    id_publicacion=models.PositiveIntegerField(default=0)

class Producto(models.Model):
    #atributos
    foto= models.ImageField(upload_to='juguetes', max_length=500)
    nombre=models.CharField(max_length=20)
    categoria=models.CharField(max_length=2, choices= Categoria, default='DV')
    Disponible_a_intercambio=models.BooleanField(default=False)

    QR = models.ImageField(upload_to='codigoQR', blank=True, null=True)

    estado=models.CharField(max_length=250, blank=True,null=True)
    marca=models.CharField(max_length=250, blank=True,null=True)
    modelo=models.CharField(max_length=250, blank=True,null=True)
    serie=models.CharField(max_length=250, blank=True,null=True)
    anno=models.CharField(max_length=250, blank=True,null=True)
    tamano=models.CharField(max_length=250, blank=True,null=True)
    material=models.CharField(max_length=250, blank=True,null=True)



    #LLaves foraneas
    galeria = models.ForeignKey(Galeria, on_delete=models.CASCADE, blank=True,null=True)


    def save(self,**kwargs):
        super(Producto, self).save()
        # self.generate_qrcode()

    def generate_qrcode(self):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        from django.conf import settings
        link= settings.ALLOWED_HOSTS[0] +":"+ settings.PORT + '/producto/verProducto/%s/%s' % (self.id, self.galeria.id)
        qr.add_data(link)
        qr.make(fit=True)
        filename = '/codigoQR/qrcode-%s.png' % self.id

        img = qr.make_image()

        img.save(settings.MEDIA_ROOT + filename)


    def __str__(self):
        return self.nombre

class Historial(models.Model):
    producto = models.OneToOneField(Producto, on_delete=models.CASCADE, blank=True,null=True)
    Registro = models.CharField(max_length=40)
    Adquisicion = models.CharField(max_length=40)
    Intercambiado = models.PositiveIntegerField()

apps/galeria/forms.py
from django.forms import ModelForm
from django import forms
from apps.galeria.models import Galeria

class GaleriaForm(forms.ModelForm):
    class Meta:
        model= Galeria

        fields=[
            'limiteProductos',
        ]
        labels={
            'limiteProductos':'Limite de juguetes a registrar:',
        }
        widgets={
            'limiteProductos':forms.NumberInput(attrs={'class':'form-control'}),
        }

    def save(self,commit=True):
        galeria=super(GaleriaForm,self).save(commit=False)
        if commit:
            galeria.save()
        return galeria

apps/galeria/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from apps.galeria.models import Galeria
from apps.usuarios.models import Apoderado, Infante
from apps.producto.models import Producto
from apps.galeria.forms import GaleriaForm

# Create your views here.
def verGaleria_ap(request,id_infante):
    data={}

    if Apoderado.objects.get(usuario_id=request.session.get('id')).rut == Infante.objects.get(id=id_infante).apoderado_id:

        data['apoderado']=Apoderado.objects.get(usuario_id=request.session.get('id'))
        data['infante']=infante=Infante.objects.get(id=id_infante)

        data['numJuguetesRegistrados']=Producto.objects.filter(galeria_id=Galeria.objects.get(infante_id=infante.id).id,Disponible_a_intercambio=True).count()
        data['numJuguetesNoRegistrados']=Producto.objects.filter(galeria_id=Galeria.objects.get(infante_id=infante.id).id,Disponible_a_intercambio=False).count()

        try:
            data['galeria']=Galeria.objects.get(infante=id_infante)
            try:
                data['productos_D']=Producto.objects.filter(galeria=Galeria.objects.get(infante=id_infante),Disponible_a_intercambio=True)
            except Producto.DoesNotExist:
                data['productos_D']=None

            try:
                data['productos_ND']=Producto.objects.filter(galeria=Galeria.objects.get(infante=id_infante),Disponible_a_intercambio=False)
            except Producto.DoesNotExist:
                data['productos_ND']=None
        except Galeria.DoesNotExist:
            data['galeria']=None
            data['productos_D']=None
            data['productos_ND']=None

        data['juguetes_num']=len(data['productos_D'])+len(data['productos_ND'])

        template_name='galerias/galeria_apoderado.html'
        return render(request,template_name,data)
    else:
        return HttpResponseRedirect(reverse('inicio_ap'))

def verGaleria_in(request,id_infante):
    data={}

    if Infante.objects.get(usuario_id=request.session.get('id')).id == id_infante:

        data['infante']=infante=Infante.objects.get(usuario_id=request.session.get('id'))
        data['numJuguetesRegistrados']=Producto.objects.filter(galeria_id=Galeria.objects.get(infante_id=infante.id).id,Disponible_a_intercambio=True).count()
        data['numJuguetesNoRegistrados']=Producto.objects.filter(galeria_id=Galeria.objects.get(infante_id=infante.id).id,Disponible_a_intercambio=False).count()

        try:
            data['galeria']=Galeria.objects.get(infante=id_infante)
            try:
                data['productos_D']=Producto.objects.filter(galeria=Galeria.objects.get(infante=id_infante),Disponible_a_intercambio=True)
            except Producto.DoesNotExist:
                data['productos_D']=None

            try:
                data['productos_ND']=Producto.objects.filter(galeria=Galeria.objects.get(infante=id_infante),Disponible_a_intercambio=False)
            except Producto.DoesNotExist:
                data['productos_ND']=None
        except Galeria.DoesNotExist:
            data['galeria']=None
            data['productos_D']=None
            data['productos_ND']=None

        data['juguetes_num']=len(data['productos_D'])+len(data['productos_ND'])


        template_name='galerias/galeria_infante.html'
        return render(request,template_name,data)
    else:
        return HttpResponseRedirect(reverse('intercambio_in'))

# def configGaleria(request, id_galeria, limite):
def configGaleria(request, id_galeria):
    data={}

    if Apoderado.objects.get(usuario_id=request.session.get('id')).rut == Infante.objects.get(id=Galeria.objects.get(id=id_galeria).infante_id).apoderado_id:

        apoderado=Apoderado.objects.get(usuario_id=request.session.get('id'))
        galeria=Galeria.objects.get(id=id_galeria)
        template_name='galerias/galeria_config.html'

        if request.method=='POST':
            limiteP = request.POST.get('limiteProductos')
            Galeria.objects.filter(id=id_galeria).update(limiteProductos=limiteP)
            return HttpResponseRedirect(reverse('galeria_config',kwargs={'id_galeria':id_galeria}))
            # return HttpResponseRedirect(reverse('galeria_config',kwargs={'id_galeria':id_galeria, 'limite':limiteP}))
        else:
            # borrar usuario
            form=GaleriaForm()

        return render(request,template_name,{'form':form, 'galeria':galeria, 'apoderado':apoderado})
    else:
        return HttpResponseRedirect(reverse('inicio_ap'))

def filtrarGaleria(request,id_infante):
    response={}
    P_disponibles=[]
    P_Nodisponibles=[]
    largoD=0
    largoND=0

    filtro=request.POST.get('filtro')

    try:
        if filtro == 'todo':
            Dis_p=Producto.objects.filter(galeria=Galeria.objects.get(infante=id_infante),Disponible_a_intercambio=True).order_by('-id')
        else:
            Dis_p=Producto.objects.filter(galeria=Galeria.objects.get(infante=id_infante),categoria=filtro,Disponible_a_intercambio=True)

    except Producto.DoesNotExist:
        Dis_p=None

    try:
        if filtro == 'todo':
            noDis_p=Producto.objects.filter(galeria=Galeria.objects.get(infante=id_infante),Disponible_a_intercambio=False).order_by('-id')
        else:
            noDis_p=Producto.objects.filter(galeria=Galeria.objects.get(infante=id_infante),categoria=filtro,Disponible_a_intercambio=False)

    except Producto.DoesNotExist:
        noDis_p=None

    for producto in Dis_p:
        largoD+=1
        P_disponibles.append([producto.pk,producto.foto.url,producto.nombre,producto.categoria])

    for producto in noDis_p:
        largoND+=1
        P_Nodisponibles.append([producto.pk,producto.foto.url,producto.nombre,producto.categoria])


    response["P_disponibles"]=P_disponibles
    response["P_Nodisponibles"]=P_Nodisponibles
    response["largoD"]=largoD
    response["largoND"]=largoND


    return JsonResponse(response)

templates/galerias/admin_galeria.html
{% extends 'indexs/index_admin.html' %}
{% load static %}

{% block menu%}
  <li>
    <a href="{% url 'inicio_ad' %}"><span class="nav-label">Usuarios</span></a>
  </li>
{% endblock %}

{% block contenido %}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title text-center">
                <h1><b>Galeria de {{infante.nombre}}</b></h1>
            </div>
            <div class="ibox-content">

                <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover dataTables-example" >
            <thead>
            <tr>
                <th >ID</th>
                <th >foto</th>
                <th >nombre</th>
                <th >categoria</th>

                <th class="text-center">Publicacion</th>
                <th class="text-center">Eliminar</th>
            </tr>
            </thead>
            <tbody>
              {% for j in juguetes %}
                <tr >
                    <td>{{j.0.id}}</td>
                    <td><img id="a{{j.0.id}}" style="width:90%" src="{{j.0.foto.url}}"></td>
                    <script>
                      var width=(screen.width/8);
                      document.getElementById("a{{j.0.id}}").style.maxWidth=width+"px";
                    </script>
                    <td>{{j.0.nombre}}</td>
                    <td>{{j.0.get_categoria_display}}</td>
                    {% if j.1 != None %}
                      <td class="text-center"><a href="{% url 'eliminar_publicacion' j.0.id infante.id %}" class="btn btn-info" role="button">Eliminar Publicación</a></td>
                    {% else %}
                      <td class="text-center"><font color="blue">-- Sin Publicar --</font></td>
                    {% endif %}

                    <td class="text-center"><a href="{% url 'eliminar_juguete' j.0.id infante.id %}" class="btn btn-info" role="button">Eliminar juguete</a></td>

                </tr>
              {% endfor %}
            </tbody>

            </table>
                </div>

            </div>
        </div>
    </div>
    </div>
</div>

{% endblock %}


{% block codigo_js %}




<script src="{% static 'Plantilla_Sistema/js/plugins/dataTables/datatables.min.js' %}"></script>


<!-- Page-Level Scripts -->
<script>
    $(document).ready(function(){
        $('.dataTables-example').DataTable({
            pageLength: 25,
            responsive: true,
            dom: '<"html5buttons"B>lTfgitp',
            buttons: [
                { extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'ExampleFile'},
                {extend: 'pdf', title: 'ExampleFile'},

                {extend: 'print',
                 customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                }
                }
            ]

        });

    });

</script>


{% endblock %}

templates/galerias/galeria_config.html
{% extends 'galerias/galeria_apoderado.html' %}
{% load static %}
{% load bootstrap %}

{% block menu%}
  <li>
      <a href="{% url 'inicio_ap' %}"><i class="fa fa-child"></i> <span class="nav-label">Mis niños</span></a>
  </li>
  <li>
      <a href="{% url 'intercambios_a_concretar' %}"><i class="fa fa-exchange"></i> <span class="nav-label">Intercambios a concretar</span><span id="n_cierres" class="label label-info pull-right"></span></a>
  </li>
  <li >
      <a href="{% url 'galeria_ap' galeria.infante.id %}"><i class="fa fa-picture-o"></i> <span class="nav-label">Galería</span></a>
  </li>
  {% endblock %}

  {% block contenido %}

  <div class="row wrapper border-bottom white-bg page-heading">
      <div class="col-lg-12">
            <h2>Configuración de Galería</h2>
            <ol class="breadcrumb">
                <a href="{% url 'galeria_ap' galeria.infante.id %}" class="btn btn-primary" role="button">Volver</a>
            </ol>
      </div>
  </div>

  <div class="wrapper wrapper-content">
            <div class="row ">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">

                    <div class="ibox-content">

                        <h2>Limite actual de juguetes: <strong>{{galeria.limiteProductos}}</strong></h2>


                        <div class="lightBoxGallery text-center">
                          <form  method="post" >
                            {% csrf_token %}

                            {{ form|bootstrap }}


                            <button type="submit" class="btn btn-primary">Aceptar</button>
                          </form>
                        </div>

                    </div>
                </div>
            </div>
            </div>
        </div>
  {% endblock %}

  {% block codigo_js %}

  <!-- cierres pendientes: -->
  <script>
  $.ajax({
    type: "POST",
    url:"{% url 'cierresPendientes' %}",
    data:{
      csrfmiddlewaretoken:"{{ csrf_token }}",
      rutApoderado:"{{apoderado.rut}}"
    },

    success: function(response){
      $("#n_cierres").html("");
      $("#n_cierres").append(''+response.numero+'');
    }
  })
  </script>

  {% endblock %}

<script src="{% static 'Plantilla_Sistema/js/plugins/blueimp/jquery.blueimp-gallery.min.js' %}"></script>